baseURL = 'https://nguyencungthanh.github.io/'
languageCode = 'en'
title = 'Nguyen Cung Thanh'
pluralizeListTitles = false
removePathAccents = true
capitalizeListTitles = true
summaryLength = 300
printPathWarnings = true

[build]
  buildFuture = true

[pagination]
  pagerSize = 15

[taxonomies]
  tag = 'tags'
  category = 'categories'

[permalinks]
  tags = '/tags/:slug/'
  categories = '/categories/:slug/'
  posts = '/:year/:month/:day/:slug/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    noClasses = false

[menu]
[[menu.main]]
  name = '🌤️ About'
  pageRef = '/about'
  weight = 1
[[menu.main]]
  name = '♾️ Mathematic Blog'
  pageRef = '/categories/writings'
  weight = 2
[[menu.main]]
  name = '🖥️ Algorithm Project'
  pageRef = '/categories/projects'
  weight = 3
[[menu.main]]
  name = '🌈 More'
  pageRef = '/more'
  weight = 5

[params]
  [params.site]
    description = "Nguyen Cung Thanh"
  [params.author]
    name = 'Nguyen Cung Thanh'
    email = 'nguyencungthanh11@gmail.com'
    handle = 'nguyencungthanh'
    identities = [
      'https://github.com/nguyencungthanh',
      'https://instagram.com/nguyencungthanh',
      'mailto:nguyencungthanh11@gmail.com'
    ]

[mediaTypes.'application/atom+xml']
  suffixes = ['xml']
[mediaTypes.'text/xsl']
  suffixes = ['xsl']

[outputFormats]
  [outputFormats.atom]
    baseName = 'feed'
    mediaType = 'application/atom+xml'
    isPlainText = false
    rel = 'alternate'
    noUgly = true
    permalinkable = false
  [outputFormats.json]
    baseName = 'feed'
    mediaType = 'application/json'
    isPlainText = true
    rel = 'alternate'
    noUgly = true
    permalinkable = false

  [outputFormats.feedXsl]
    baseName = 'feed'
    mediaType = 'text/xsl'
    isPlainText = true
    notAlternative = true
    noUgly = true
  [outputFormats.SearchIndex]
    baseName = 'search'
    mediaType = 'application/json'
    isPlainText = true
    notAlternative = true
    noUgly = true
  [outputFormats.sitemapXsl]
    baseName = 'sitemap'
    mediaType = 'text/xsl'
    isPlainText = true
    notAlternative = true
    noUgly = true

[outputs]
  taxonomy = ['HTML']
  term = ['HTML', 'ATOM', 'JSON']
  home = ['HTML', 'ATOM', 'JSON', 'FEEDXSL', 'SITEMAPXSL', 'SearchIndex']
  section = ['HTML']
  page = ['HTML']

[services]
  [services.rss]
    limit = 10
